CREATE TABLE IF NOT EXISTS RSTR
(
  sourceFacility VARCHAR (1024),
  sourceTimestamp TIMESTAMP WITH TIME ZONE,
  sensitivity VARCHAR (1024),
  eventTime TIMESTAMP WITH TIME ZONE,
  entryTime TIMESTAMP WITH TIME ZONE,
  facility VARCHAR (1024),
  action BIGINT,
  restrictionId BIGINT,
  restrictedNasElements VARCHAR (1024),
  startTime TIMESTAMP WITH TIME ZONE,
  stopTime TIMESTAMP WITH TIME ZONE,
  airports VARCHAR(1024),
  aircraftType VARCHAR(1024),
  restrictionType INTEGER,
  mitNumber BIGINT,
  mitValue INTEGER,
  altitude VARCHAR(1024),
  speed INTEGER,
  reasonText VARCHAR(1024),
  impactedElements VARCHAR(1024),
  qualifier VARCHAR(1024),
  passback VARCHAR(1),
  exclusions VARCHAR(1024),
  approvalTime TIMESTAMP WITH TIME ZONE,
  providerStatus VARCHAR(1024),
  referenceRestrictionEndTime VARCHAR(1024),
  refreenceRestrictionId BIGINT,
  remarks VARCHAR(1024),
  createdAt TIMESTAMP WITH TIME ZONE default now()
);
