{
 "title": "Airport Configuration",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "airport", "query": "select airport from aptc" }
  ]
 },
 "panels": [
  {
   "title": "Active Departure Runway",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  deprunwayconf AS metric\nFROM aptc\nWHERE airport = '$airport' AND deprunwayconf != ' '\nORDER BY createdat desc\nlimit 2"
    }
   ]
  },
  {
   "title": "Active Arrival Runway",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  arrrunwayconf AS metric\nFROM aptc\nWHERE airport = '$airport' AND arrrunwayconf != ' '\nORDER BY createdat desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Departure Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(createdat,$__interval),\n  airport AS airport,\n  deprate\nFROM aptc\nWHERE\n  airport = ('$airport') AND $__timeFilter(createdat) AND deprate > 0\nGROUP BY 1,2,3\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Arrival Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(createdat,$__interval),\n  airport AS airport,\n  arrrate\nFROM aptc\nWHERE\n  airport =('$airport') AND $__timeFilter(createdat) AND arrrate > 0\nGROUP BY 1,2,3\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Airport Configurations",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "select createdat as \"Time\",\nairport as \"Airport\",\ndeprunwayconf as \"Departure Runway\",\ndeprate as \"Departure Rate\",\narrrunwayconf  as \"Arrival Runway\",\narrrate  as \"Arrival Rate\"\nfrom aptc where airport =('$airport') AND $__timeFilter(createdat) order by createdat\n"
    }
   ]
  }
 ]
}