{
 "title": "Restrictions",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "facility", "query": "select facility from rstr" },
   {
    "name": "airports",
    "query": "select airports from rstr where facility in ($facility)"
   },
   {
    "name": "reason",
    "query": "select split_part(reasontext,':',1) from rstr order by reasontext"
   }
  ]
 },
 "panels": [
  {
   "title": "Restrictions Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select count(*) as rstr from rstr where airports in($airports) AND facility in($facility) AND $__timeFilter(createdat) AND split_part(reasontext,':',1) in ($reason) "
    }
   ]
  },
  {
   "title": "Restrictions by Airport",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(createdat,$__interval),\n  airports AS ariport,\n  count(*) AS \"count\"\nFROM rstr\nWHERE\n  airports in($airports) AND facility in($facility) AND $__timeFilter(createdat) AND split_part(reasontext,':',1) in ($reason) \nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Restrictions",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "select createdat as \"Time\",\nsourcefacility as \"Facility\",\nstartTime as \"Start\",\nstoptime as \"Stop\",\nstoptime - starttime as \"Duration\",\nairports as \"Airports\",\naircrafttype as \"Aircraft\",\nrestrictednaselements as \"Restricted Elements\",\nreasontext as \"Reason\"\nfrom rstr where airports in($airports) AND facility in($facility) AND $__timeFilter(createdat) AND split_part(reasontext,':',1) in ($reason) order by createdat\n"
    }
   ]
  }
 ]
}