{
 "title": "D-ATIS",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "airport", "query": "select airport from tdes" }
  ]
 },
 "panels": [
  {
   "title": "D-ATIS Airports",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct airport)\nFROM\n  tdes\nWHERE\n  $__timeFilter(createdat)"
    }
   ]
  },
  {
   "title": "D-ATIS Message Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(airport)\nFROM\n  tdes\nWHERE\n  $__timeFilter(createdat)\n  AND airport in ($airport)\n"
    }
   ]
  },
  {
   "title": "D-ATIS Messages",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "select * from (\n  select createdat, airport, body, row_number() over (partition by airport order by createdat desc) as rownum from tdes\n) tmp\nwhere rownum < 2 AND $__timeFilter(createdat) AND airport in ($airport)\norder by createdat desc"
    }
   ]
  }
 ]
}